FROM python:3.12-slim
RUN pip install poetry && \
    poetry config virtualenvs.in-project true
WORKDIR /app
COPY pyproject.toml poetry.lock ./
RUN poetry install
COPY . .
CMD poetry run python main.py